//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string league { get; set; }
        public string club { get; set; }
        public string nation { get; set; }
        public string position { get; set; }
    }
}
